### ISSUE TITLE
1.0.0.8版本唤醒快捷键失效

### ISSUE THREAD

**Issue by Git3012166280** [25H/MayeLite#12]
"HotKey": "Alt+Space",
不起作用

**Comment by 25H** [comment]
还没发

**Comment by Git3012166280** [comment]
新版快捷键 不生效怎么回事？

**Comment by 25H** [comment]
改为`"HotKey": "VK.LALT+VK.SPACE",`

**Comment by Git3012166280** [comment]
> 改为`"HotKey": "VK.LALT+VK.SPACE",`

也一样 不生效

{
	"HotKey": "VK.LALT+VK.SPACE",
	"InputModeTriggerKey": 0,
	"IsDebug": false,
	"IsDoubleClickBlankHide": false,
	"IsKillFocuHide": false,
	"IsMouseWheelRun": true,
	"IsNotifyIconHoverShow": true,
	"IsRunAfterHide": true,
	"IsTopMost": true,
	"NotifyIconType": 0,
	"TabHoverSwitchDelay": 0,
	"cx": 1005,
	"cy": 688,
	"minSpareChildProcess": 0,
	"x": 393,
	"y": 63
}

**Comment by 25H** [comment]
是个bug，目前解决方法，随意给项目设置一个快捷键即可

**Comment by Git3012166280** [comment]
> 

好的 解决了 谢谢
