### ISSUE TITLE
HotKey不起作用了

### ISSUE THREAD

**Issue by cbabc0311** [25H/MayeLite#15]
最新版HotKey失灵了？

**Comment by 25H** [comment]
具体是什么地方，唤醒快捷键还是项目快捷键，如果是唤醒，将cfg.json发出来我看一下

**Comment by Hanshan8023** [comment]
我也出现了同样的问题，cfg.json文件中的键值对: 

`"HotKey": "VK.LMENU+VK.SPACE"`

是不是需要重启电脑才会生效?

**Comment by cbabc0311** [comment]
{
	"HotKey": "Win+Alt+Space",
	"InputModeTriggerKey": 0,
	"IsDebug": false,
	"IsDoubleClickBlankHide": true,
	"IsKillFocuHide": true,
	"IsMouseWheelRun": true,
	"IsNotifyIconHoverShow": true,
	"IsRunAfterHide": true,
	"IsTopMost": true,
	"NotifyIconType": -1,
	"TabHoverSwitchDelay": 200,
	"cx": 551,
	"cy": 500,
	"minSpareChildProcess": 0,
	"theme": "dark.css",
	"x": 564,
	"y": 267
}

**Comment by cbabc0311** [comment]
1.0.0.6正常，1.0.0.7没试

**Comment by 25H** [comment]
改为`"HotKey": "VK.LALT+VK.SPACE",`

**Comment by cbabc0311** [comment]
> 改为`"HotKey": "VK.LALT+VK.SPACE",`

谢谢，试了试，还是不起作用。

**Comment by 25H** [comment]
是个bug，目前解决方法，随意给项目设置一个快捷键即可
