### ISSUE TITLE
下载报毒内容的补充

### ISSUE THREAD

**Issue by valuex** [25H/MayeLite#24]
我看有人反馈了Win11+Windows Defender 报毒的问题。
我再补充电信息，Windows Defender 报毒的具体内容如下：
刚好下载过MayeLite-11.3.0.2306028和MayeLite-11.4.0.230608， 这两个版本是没有报毒的。

![image](https://github.com/25H/MayeLite/assets/3627812/70050ba0-d8ec-40b3-8ac5-47bafee4c072)

**Comment by 25H** [comment]
我这刚刚测试`11.5.1.230613`这个没报毒，那个不太清楚具体时什么问题
