### ISSUE TITLE
[功能请求]希望能在检测到程序全屏时自动开启勿扰模式

### ISSUE THREAD

**Issue by cuddly-guacamole** [25H/MayeLite#25]
我设置的快捷键是“VK.LALT+VK.SPACE”，在全屏打LOL时有时单独按Alt键或Space键时会莫名其妙地触发MayeLite。（可能是我电脑太卡的原因。）（这种情况是发生在11.4.1.230608版本。）
因此，我希望添加设置项“在检测到程序全屏时自动开启勿扰模式”。

**Comment by 25H** [comment]
托盘右键有个勿扰模式
