### ISSUE TITLE
lite不支持便携路径吗？

### ISSUE THREAD

**Issue by Joackk** [25H/MayeLite#29]
把maye的设置的存储用文件直接拷过来使用的时候，发现使用了便携路径的全部成了乱码无法正常使用，是lite不支持便携路径吗？便携路径还挺方便的，又时候盘符不一样了也不会找不到

**Comment by 25H** [comment]
支持，但maye复制到lite需要将JDB文件转换成utf8编码

**Comment by Joackk** [comment]
> 支持，但maye复制到lite需要将JDB文件转换成utf8编码

soga，lite这里似乎没有转换便携路径的选项哇

**Comment by 25H** [comment]
暂不支持路径转换，未来会加入
