### ISSUE TITLE
MayeLite可以直接拖图标文件添加进去吗

### ISSUE THREAD

**Issue by xivi1839** [25H/MayeLite#35]
MayeLite可以直接拖图标文件添加进去吗，

Maye可以直接拖添加，MayeLite就没办法直接拖添加，可以增加这个吗

**Comment by 25H** [comment]
如果无法拖入到mayelite，关闭拖放增强即可，关闭后需重启mayelite

**Comment by xivi1839** [comment]
解决了，谢谢
