### ISSUE TITLE
设置跟随鼠标后，双击链接，界面会莫名其妙往上偏移

### ISSUE THREAD

**Issue by daerzi** [25H/MayeLite#47]
设置跟随鼠标后，双击链接，界面会莫名其妙往上偏移，不设置跟随鼠标是正常的，这是为啥。

**Comment by 25H** [comment]
录个视频或是gif我看下

**Comment by daerzi** [comment]
![动画](https://github.com/25H/MayeLite/assets/72557859/0b7e6840-c63c-423d-ba2c-e1b9f5d0c905)

**Comment by daerzi** [comment]
> 录个视频或是gif我看下

![动画](https://github.com/25H/MayeLite/assets/72557859/03d43dcd-8152-460e-8f62-6481a3dce248)

**Comment by daerzi** [comment]
gif
