### ISSUE TITLE
json文件乱码，配置丢失

### ISSUE THREAD

**Issue by sglmsn** [25H/MayeLite#50]
当我通过这个程序启动了OpenArk64.exe，并且 试图进入内核模式的时候，系统奔溃自动重启，重启之后，maye的配置全部没了，打开JDB.json发现全部成了乱码

**Comment by 25H** [comment]
将jdb文件发送到`su@arae.cc`我看下，另外lite目前没有自动备份

**Comment by sglmsn** [comment]
> 将jdb文件发送到`su@arae.cc`我看下，另外lite目前没有自动备份

我看到乱码的时候,就把文件给删了,然后让程序重新生成了一份,刚刚我想试图重新崩溃,但是没能成功

**Comment by 25H** [comment]
目前建议经常备份jdb文件，为了我会加入相关自动功能
