### ISSUE TITLE
建议增强界面设置功能

### ISSUE THREAD

**Issue by itspidercn** [25H/MayeLite#54]
非常感谢开发出这么好用的工具，现在已经是最新的v12.4.0.240110
几个版本用下来，提两个最迫切的需求：
1、允许自定义图标宽度。
现在仅能通过设置大中小图标来粗略调整，大图标能显示的名称字数稍多，但想更多一些就不行了。

2、允许自定义图标“编辑”界面中各栏字符型控件的高度。
尤其是“备注”，现在只有一行，用着比较别扭。我要记录该软件的版本号、优缺点，甚至简要的操作提示，能多几行会方便很多。

谢谢！

**Comment by 25H** [comment]
自定义宽度这个不打算实现了，

多行备注是支持的
![Snipaste_2024-01-12_02-26-05](https://github.com/25H/MayeLite/assets/36186834/fa2729fc-b154-4786-81d5-ce55fc3b5b9c)
![Snipaste_2024-01-12_02-25-46](https://github.com/25H/MayeLite/assets/36186834/704f95dd-bb5c-4344-a147-ce11ea6fa5ef)

**Comment by 25H** [comment]
右下角可以调整输入框的宽高

**Comment by itspidercn** [comment]
> 右下角可以调整输入框的宽高

thx，这是个隐藏技能，学习到了，呵呵
