### ISSUE TITLE
开机自启速度很慢等开机问题

### ISSUE THREAD

**Issue by xi45** [25H/MayeLite#59]
1.别的小插件都非常的迅速打开，但这个开机自启就非常缓慢，总是要等很久，在最后才出现。一开机就准备用起结果老半天没有响应，这样的体验实在是不太舒服
2.开机自启的设置也经常失效，在启动目录里放入图标的方式也试过，网上的各种开机自启的方式也试过，但效果还是不太好，虽然不是百分百不能自启，但存在一定的几率。
3.而且自启打开后也有一定几率是最大化的形态，而不是隐藏在托盘里。

**Comment by 25H** [comment]
mayelite启动默认是不显示的，如果显示可能是误触了唤醒键，
