### ISSUE TITLE
BUG :内存泄漏

### ISSUE THREAD

**Issue by sjhsbhqf** [25H/MayeLite#68]
![image](https://github.com/25H/MayeLite/assets/41407099/5def20a9-064a-4a93-af49-ff77ec542041)

如上图所示，启动PS之后，内存暴涨

PS关闭之后，这个所谓的maye lite launcher进程也会被关闭

**Comment by 25H** [comment]
可以提供ps的下载地址吗，我这里测试下

**Comment by sjhsbhqf** [comment]
> 可以提供ps的下载地址吗，我这里测试下

不好意思，我发现后面再难复现这个问题了。所以即使给你ps的下载安装教程，可能也难复现这个情况；不过如果你需要的话，我很愿意发出来。

我在之后做了两件事，一个是把百度网盘的资源管理器插件禁用，另一个是把百度网盘的一个导致IO读写的文件改为只读。

看起来跟ps软件和maye lite无关，但是我怀疑是不是跟资源管理器插件之类的相关?

**Comment by sjhsbhqf** [comment]
当时，加载ps的内存全在maye launcher程序进程里，ps加载完成还是如此

**Comment by 25H** [comment]
两个完全独立的进程，理论不会出现这种问题🤷‍♂️

**Comment by sjhsbhqf** [comment]
> 两个完全独立的进程，理论不会出现这种问题🤷‍♂️

好的，谢谢大哥，还有就是希望大哥改进一下更新软件的流程，能够直接实现在软件内部更新最好了。
