### ISSUE TITLE
希望添加停靠屏幕边缘时吸附

### ISSUE THREAD

**Issue by xiaoxin6182** [25H/MayeLite#7]
希望后期能添加停靠屏幕边缘时吸附，这个功能经常用。

还有一个功能，不知道Maye能否做到，就是快捷键呼出Maya时能把输入法自动切换为英文，这样搜索的速度非常快

**Comment by Joackk** [comment]
希望能加入边缘吸附和双击运行的设置

**Comment by 25H** [comment]
目前暂不添加，没空搞
